name: PROJECT-GTIS-App-Control

on:
  workflow_call:
    inputs:
      server:
        required: true
        type: string
      vault-folder:
        required: true
        type: string
      action:
        required: true
        type: string
      email-address:
        required: true
        type: string
      email-subject:
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ inputs.server }} >> ~/.ssh/known_hosts

      - name: Fetch secrets from Vault
        run: |
          echo "Simulating fetching secrets from Vault folder ${{ inputs.vault-folder }}"

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Run the requested script
        run: |
          ./scripts/${{ inputs.action }}.sh ${{ inputs.server }}

      - name: On failure notify via email
        if: failure()
        run: |
          echo "Sending failure notification to ${{ inputs.email-address }}"
