name: PROJECT-GTIS-App-Control

on:
  workflow_call:
    inputs:
      server:
        required: true
        type: string
      vault-folder:
        required: true
        type: string
      action:
        required: true
        type: string
      email-address:
        required: true
        type: string
      email-subject:
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Run the requested script
        run: |
          ./scripts/${{ inputs.action }}.sh ${{ inputs.server }}

      - name: On failure notify via email
        if: failure()
        run: |
          echo "Sending failure notification to ${{ inputs.email-address }}"
