name: RUN-GTIS-App-Control-DEV

on:
  workflow_dispatch:
    inputs:
      server:
        description: "Input into build for variable(${server})"
        required: false
        default: "test-server"
      action:
        description: "Choose which remote script to run (startup or shutdown)"
        required: true
        default: "startup"
      vault-folder:
        description: "Vault environment folder"
        required: true
        default: "apps/sample-app"

permissions:
  actions: read
  id-token: write
  security-events: write
  contents: read

jobs:
  app-control:
    uses: dukeenergy-corp/ngas_comops-build-deployment-repo/.github/workflows/PROJECT-GTIS-App-Control.yaml@master
    with:
      server: ${{ github.event.inputs.server }}
      vault-folder: ${{ github.event.inputs.vault-folder }}
      ACTION: ${{ github.event.inputs.action }}
