name: RUN-GTIS-App-Control

on:
  workflow_dispatch:
    inputs:
      server:
        required: true
        type: string
      vault-folder:
        required: true
        type: string
      action:
        required: true
        type: string
      email-address:
        required: true
        type: string
      email-subject:
        required: true
        type: string

jobs:
  trigger-project-workflow:
    uses: ./.github/workflows/PROJECT-GTIS-App-Control.yaml
    with:
      action: ${{ github.event.inputs.action }}
      email-address: ${{ github.event.inputs.email-address }}
      
