name: RUN-GTIS-App-Control-DEV

on:
  workflow_dispatch:
    inputs:
      server:
        description: "Hostname or IP of the remote server"
        required: false
        type: string
        default: "gtis-app-dev01.mycompany.internal"  # <-- Update this to your actual server hostname or IP
      action:
        description: "Choose which remote script to run"
        required: true
        default: "startup"
        type: choice
        options:
          - startup
          - shutdown
      vault-folder:
        description: "Vault environment folder"
        required: true
        default: "dev"
        type: string

jobs:
  app-control:
    permissions:
      actions: read
      id-token: write
      security-events: write
      contents: read

    uses: dukeenergy-corp/ngas_comops-build-deployment-repo/.github/workflows/PROJECT-GTIS-App-Control.yaml@master
    with:
      ACTION: ${{ github.event.inputs.action }}
      server: ${{ inputs.server }}
      vault-folder: ngas-gtis/${{ inputs.vault-folder }}/ssh
